"""HTML report generation from backtest artifacts."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional


# ------------------------------------------------------------------ template

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Backtest Report - {symbol}</title>
  <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
  <style>
    :root {{ --bg: #0d1117; --surface: #161b22; --border: #30363d;
             --text: #e6edf3; --muted: #8b949e; --green: #3fb950; --red: #f85149; }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: var(--bg); color: var(--text); font-family: -apple-system, sans-serif;
            font-size: 14px; line-height: 1.6; padding: 24px; max-width: 1200px; margin: 0 auto; }}
    header {{ border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 24px; }}
    header h1 {{ font-size: 22px; font-weight: 600; }}
    header p {{ color: var(--muted); font-size: 12px; margin-top: 4px; }}
    h2 {{ font-size: 16px; font-weight: 600; margin: 24px 0 12px; }}
    .metrics-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
                     gap: 12px; margin-bottom: 24px; }}
    .metric-card {{ background: var(--surface); border: 1px solid var(--border);
                    border-radius: 6px; padding: 12px 16px; }}
    .metric-card .label {{ color: var(--muted); font-size: 11px; text-transform: uppercase;
                           letter-spacing: 0.5px; }}
    .metric-card .value {{ font-size: 20px; font-weight: 600; margin-top: 4px; }}
    .metric-card .value.pos {{ color: var(--green); }}
    .metric-card .value.neg {{ color: var(--red); }}
    .chart {{ background: var(--surface); border: 1px solid var(--border);
              border-radius: 6px; margin-bottom: 16px; padding: 8px; }}
    table {{ width: 100%; border-collapse: collapse; background: var(--surface);
             border: 1px solid var(--border); border-radius: 6px; overflow: hidden; }}
    th {{ background: var(--border); padding: 8px 12px; text-align: left;
          font-size: 11px; text-transform: uppercase; color: var(--muted); }}
    td {{ padding: 8px 12px; border-top: 1px solid var(--border); font-size: 12px; }}
    footer {{ color: var(--muted); font-size: 11px; text-align: center;
              margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border); }}
  </style>
</head>
<body>
  <header>
    <h1>Backtest Report &mdash; {symbol}</h1>
    <p>Run ID: {run_id} &nbsp;|&nbsp; Generated: {generated} &nbsp;|&nbsp;
       Period: {start} to {end} &nbsp;|&nbsp; Strategy: {strategy}</p>
  </header>

  <h2>Summary</h2>
  <div class="metrics-grid">
{metric_cards}
  </div>

  <h2>Equity &amp; Drawdown</h2>
  <div class="chart" id="equity-chart"></div>

  <h2>Return Distribution</h2>
  <div class="chart" id="returns-hist"></div>

  <h2>Trade Log</h2>
{trades_table}

  <footer>Generated by bttool &nbsp;|&nbsp; Project Paradise Backtester</footer>

  <script>
    var equity_data = {equity_json};
    var returns_data = {returns_json};
    var trades_data = {trades_json};

    // Equity + Drawdown chart
    var eq_trace = {{
      x: equity_data.timestamps, y: equity_data.equity,
      type: 'scatter', name: 'Equity', line: {{color: '#58a6ff', width: 1.5}}
    }};
    var dd_trace = {{
      x: equity_data.timestamps, y: equity_data.drawdown,
      type: 'scatter', name: 'Drawdown', fill: 'tozeroy',
      line: {{color: '#f85149', width: 1}}, yaxis: 'y2'
    }};
    Plotly.newPlot('equity-chart', [eq_trace, dd_trace], {{
      paper_bgcolor: 'transparent', plot_bgcolor: 'transparent',
      font: {{color: '#e6edf3', size: 11}},
      xaxis: {{gridcolor: '#21262d', showgrid: true}},
      yaxis: {{gridcolor: '#21262d', title: 'Portfolio Value'}},
      yaxis2: {{overlaying: 'y', side: 'right', title: 'Drawdown',
                tickformat: '.1%', gridcolor: 'transparent'}},
      legend: {{bgcolor: 'transparent'}},
      margin: {{t: 20, r: 60, b: 40, l: 60}}
    }}, {{responsive: true}});

    // Returns histogram
    Plotly.newPlot('returns-hist', [{{
      x: returns_data.returns, type: 'histogram', nbinsx: 50,
      marker: {{color: '#3fb950', opacity: 0.7}}
    }}], {{
      paper_bgcolor: 'transparent', plot_bgcolor: 'transparent',
      font: {{color: '#e6edf3', size: 11}},
      xaxis: {{gridcolor: '#21262d', title: 'Period Return', tickformat: '.2%'}},
      yaxis: {{gridcolor: '#21262d', title: 'Frequency'}},
      margin: {{t: 20, r: 20, b: 50, l: 60}}
    }}, {{responsive: true}});
  </script>
</body>
</html>
"""


# ------------------------------------------------------------------ helpers

def _metric_card(label: str, value, fmt: str, flip_color: bool = False) -> str:
    if value is None:
        return f'    <div class="metric-card"><div class="label">{label}</div><div class="value">—</div></div>'
    formatted = fmt.format(value)
    css = ""
    if isinstance(value, float):
        positive = value > 0
        if flip_color:
            positive = not positive
        css = ' pos' if positive else ' neg'
    return (
        f'    <div class="metric-card">'
        f'<div class="label">{label}</div>'
        f'<div class="value{css}">{formatted}</div>'
        f'</div>'
    )


def _trades_table(trades_df) -> str:
    if trades_df is None or len(trades_df) == 0:
        return "<p style='color:var(--muted)'>No trades recorded.</p>"

    cols = ["entry_time", "exit_time", "direction", "size", "entry_price", "exit_price", "pnl", "return"]
    headers = "".join(f"<th>{c.replace('_', ' ').title()}</th>" for c in cols if c in trades_df.columns)
    rows = ""
    for _, row in trades_df.head(200).iterrows():
        cells = ""
        for c in cols:
            if c not in trades_df.columns:
                continue
            v = row[c]
            if c in ("pnl", "return") and isinstance(v, float):
                color = "color:var(--green)" if v >= 0 else "color:var(--red)"
                fmt = f"{v:.2%}" if c == "return" else f"{v:.4f}"
                cells += f'<td style="{color}">{fmt}</td>'
            else:
                cells += f"<td>{v}</td>"
        rows += f"<tr>{cells}</tr>"

    return f"<table><thead><tr>{headers}</tr></thead><tbody>{rows}</tbody></table>"


# ------------------------------------------------------------------ main

def generate_html_report(run_dir: Path, details: Dict[str, Any]) -> Path:
    """Generate report.html in the run directory. Returns path to written file."""
    import json as _json

    cfg = details.get("config", {})
    metrics = details.get("metrics", {})
    data_cfg = cfg.get("data", {}) if isinstance(cfg, dict) else {}
    strategy_cfg = cfg.get("strategy", {}) if isinstance(cfg, dict) else {}

    symbol = data_cfg.get("symbol") or "-"
    run_id = details.get("run_id", "")
    start = data_cfg.get("start") or "-"
    end = data_cfg.get("end") or "-"
    strategy = strategy_cfg.get("name") or strategy_cfg.get("file") or "-"
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Metric cards
    cards = [
        _metric_card("Total Return",      metrics.get("total_return"),      "{:.2%}"),
        _metric_card("Annualized Return", metrics.get("annualized_return"), "{:.2%}"),
        _metric_card("Sharpe Ratio",      metrics.get("sharpe_ratio"),      "{:.2f}"),
        _metric_card("Sortino Ratio",     metrics.get("sortino_ratio"),     "{:.2f}"),
        _metric_card("Max Drawdown",      metrics.get("max_drawdown"),      "{:.2%}", flip_color=True),
        _metric_card("Win Rate",          metrics.get("win_rate"),          "{:.1%}"),
        _metric_card("Profit Factor",     metrics.get("profit_factor"),     "{:.2f}"),
        _metric_card("Total Trades",      metrics.get("total_trades"),      "{}"),
    ]

    # Chart data
    equity_json = '{"timestamps":[],"equity":[],"drawdown":[]}'
    returns_json = '{"returns":[]}'
    trades_df = None

    try:
        import pandas as pd
        eq_path = run_dir / "equity.parquet"
        if eq_path.exists():
            eq = pd.read_parquet(eq_path)
            equity_json = _json.dumps({
                "timestamps": eq.index.strftime("%Y-%m-%dT%H:%M:%S").tolist(),
                "equity": eq["equity"].tolist(),
                "drawdown": eq["drawdown"].tolist(),
            })
    except Exception:
        pass

    try:
        import pandas as pd
        ret_path = run_dir / "returns.parquet"
        if ret_path.exists():
            ret = pd.read_parquet(ret_path)
            returns_json = _json.dumps({"returns": ret["returns"].dropna().tolist()})
    except Exception:
        pass

    try:
        import pandas as pd
        tr_path = run_dir / "trades.csv"
        if tr_path.exists():
            trades_df = pd.read_csv(tr_path)
    except Exception:
        pass

    html = _HTML_TEMPLATE.format(
        symbol=symbol,
        run_id=run_id[:16] + "...",
        generated=generated,
        start=start,
        end=end,
        strategy=strategy,
        metric_cards="\n".join(cards),
        equity_json=equity_json,
        returns_json=returns_json,
        trades_json="{}",
        trades_table=_trades_table(trades_df),
    )

    out = run_dir / "report.html"
    out.write_text(html, encoding="utf-8")
    return out
